local a=MogIt_Armory.AddRealm
a(1,"eu","talnivarr","Talnivarr","PvP","Normal","English")
a(2,"eu","wildhammer","Wildhammer","PvE","Normal","English")
a(3,"eu","agamaggan","Agamaggan","PvP","Normal","English")
a(4,"eu","ashenvale","Ashenvale","PvP","Normal","Russian")
a(5,"eu","thrall","Thrall","PvE","Normal","German")
a(6,"eu","argent-dawn","Argent Dawn","PvE","RP","English")
a(7,"eu","blackmoore","Blackmoore","PvP","Normal","German")
a(8,"eu","stormrage","Stormrage","PvE","Normal","English")
a(9,"eu","die-arguswacht","Die Arguswacht","PvP","RP","German")
a(10,"eu","ahnqiraj","Ahn'Qiraj","PvP","Normal","English")
a(11,"eu","die-todeskrallen","Die Todeskrallen","PvP","RP","German")
a(12,"eu","terrordar","Terrordar","PvP","Normal","German")
a(13,"eu","trollbane","Trollbane","PvP","Normal","English")
a(14,"eu","ravenholdt","Ravenholdt","PvP","RP","English")
a(15,"eu","steamwheedle-cartel","Steamwheedle Cartel","PvE","RP","English")
a(16,"eu","sinstralis","Sinstralis","PvP","Normal","French")
a(17,"eu","silvermoon","Silvermoon","PvE","Normal","English")
a(18,"eu","emerald-dream","Emerald Dream","PvE","Normal","English")
a(19,"eu","das-konsortium","Das Konsortium","PvP","RP","German")
a(20,"eu","eldrethalas","Eldre'Thalas","PvP","Normal","French")
a(21,"eu","terokkar","Terokkar","PvE","Normal","English")
a(22,"eu","onyxia","Onyxia","PvP","Normal","German")
a(23,"eu","twilights-hammer","Twilight's Hammer","PvP","Normal","English")
a(24,"eu","alakir","Al'Akir","PvP","Normal","English")
a(25,"eu","stormscale","Stormscale","PvP","Normal","English")
a(26,"eu","frostmane","Frostmane","PvP","Normal","English")
a(27,"eu","taerar","Taerar","PvP","Normal","German")
a(28,"eu","ysondre","Ysondre","PvP","Normal","French")
a(29,"eu","gilneas","Gilneas","PvE","Normal","German")
a(30,"eu","thermaplugg","Thermaplugg","PvP","Normal","Russian")
a(31,"eu","sargeras","Sargeras","PvP","Normal","French")
a(32,"eu","drakthul","Drak'thul","PvP","Normal","English")
a(33,"eu","deathguard","Deathguard","PvP","Normal","Russian")
a(34,"eu","ambossar","Ambossar","PvE","Normal","German")
a(35,"eu","frostwhisper","Frostwhisper","PvP","Normal","English")
a(36,"eu","rashgarroth","Rashgarroth","PvP","Normal","French")
a(37,"eu","galakrond","Galakrond","PvE","Normal","Russian")
a(38,"eu","nagrand","Nagrand","PvE","Normal","English")
a(39,"eu","daggerspine","Daggerspine","PvP","Normal","English")
a(40,"eu","nordrassil","Nordrassil","PvE","Normal","English")
a(41,"eu","dun-morogh","Dun Morogh","PvE","Normal","German")
a(42,"eu","executus","Executus","PvP","Normal","English")
a(43,"eu","lordaeron","Lordaeron","PvE","Normal","German")
a(44,"eu","tichondrius","Tichondrius","PvE","Normal","German")
a(45,"eu","theradras","Theradras","PvP","Normal","German")
a(46,"eu","naxxramas","Naxxramas","PvP","Normal","French")
a(47,"eu","kelthuzad","Kel'Thuzad","PvP","Normal","German")
a(48,"eu","scarshield-legion","Scarshield Legion","PvP","RP","English")
a(49,"eu","jaedenar","Jaedenar","PvP","Normal","English")
a(50,"eu","voljin","Vol'jin","PvE","Normal","French")
a(51,"eu","twisting-nether","Twisting Nether","PvP","Normal","English")
a(52,"eu","boulderfist","Boulderfist","PvP","Normal","English")
a(53,"eu","well-of-eternity","Well of Eternity","PvE","Normal")
a(54,"eu","baelgun","Baelgun","PvE","Normal","German")
a(55,"eu","perenolde","Perenolde","PvE","Normal","German")
a(56,"eu","uldaman","Uldaman","PvE","Normal","French")
a(57,"eu","gorgonnash","Gorgonnash","PvP","Normal","German")
a(58,"eu","auchindoun","Auchindoun","PvP","Normal","English")
a(59,"eu","balnazzar","Balnazzar","PvP","Normal","English")
a(60,"eu","nerzhul","Ner'zhul","PvP","Normal","French")
a(61,"eu","hakkar","Hakkar","PvP","Normal","English")
a(62,"eu","haomarush","Haomarush","PvP","Normal","English")
a(63,"eu","kaelthas","Kael'thas","PvP","Normal","French")
a(64,"eu","madmortem","Madmortem","PvE","Normal","German")
a(65,"eu","kiljaeden","Kil'jaeden","PvP","Normal","German")
a(66,"eu","chants-eternels","Chants éternels","PvE","Normal","French")
a(67,"eu","outland","Outland","PvP","Normal","English")
a(68,"eu","saurfang","Saurfang","PvE","Normal","English")
a(69,"eu","arakarahm","Arak-arahm","PvP","Normal","French")
a(70,"eu","mannoroth","Mannoroth","PvP","Normal","German")
a(71,"eu","defias-brotherhood","Defias Brotherhood","PvP","RP","English")
a(72,"eu","forscherliga","Forscherliga","PvE","RP","German")
a(73,"eu","azuregos","Azuregos","PvE","Normal","Russian")
a(74,"eu","der-abyssische-rat","Der abyssische Rat","PvP","RP","German")
a(75,"eu","darksorrow","Darksorrow","PvP","Normal","English")
a(76,"eu","anetheron","Anetheron","PvP","Normal","German")
a(77,"eu","xavius","Xavius","PvP","Normal","English")
a(78,"eu","alleria","Alleria","PvE","Normal","German")
a(79,"eu","malygos","Malygos","PvE","Normal","German")
a(80,"eu","lightnings-blade","Lightning's Blade","PvP","Normal","English")
a(81,"eu","zenedar","Zenedar","PvP","Normal","English")
a(82,"eu","shattered-halls","Shattered Halls","PvP","Normal","English")
a(83,"eu","die-nachtwache","Die Nachtwache","PvE","RP","German")
a(84,"eu","culte-de-la-rive-noire","Culte de la Rive noire","PvP","RP","French")
a(85,"eu","emeriss","Emeriss","PvP","Normal","English")
a(86,"eu","malorne","Malorne","PvE","Normal","German")
a(87,"eu","grom","Grom","PvP","Normal","Russian")
a(88,"eu","nethersturm","Nethersturm","PvE","Normal","German")
a(89,"eu","chromaggus","Chromaggus","PvP","Normal","English")
a(90,"eu","cthun","C'Thun","PvP","Normal","Spanish")
a(91,"eu","moonglade","Moonglade","PvE","RP","English")
a(92,"eu","nerathor","Nera'thor","PvP","Normal","German")
a(93,"eu","quelthalas","Quel'Thalas","PvE","Normal","English")
a(94,"eu","alonsus","Alonsus","PvE","Normal","English")
a(95,"eu","hyjal","Hyjal","PvE","Normal","French")
a(96,"eu","zuluhed","Zuluhed","PvP","Normal","German")
a(97,"eu","aszune","Aszune","PvE","Normal","English")
a(98,"eu","dunemaul","Dunemaul","PvP","Normal","English")
a(99,"eu","booty-bay","Booty Bay","PvP","Normal","Russian")
a(100,"eu","azshara","Azshara","PvP","Normal","German")
a(101,"eu","rexxar","Rexxar","PvE","Normal","German")
a(102,"eu","antonidas","Antonidas","PvE","Normal","German")
a(103,"eu","ravencrest","Ravencrest","PvP","Normal","English")
a(104,"eu","earthen-ring","Earthen Ring","PvE","RP","English")
a(105,"eu","archimonde","Archimonde","PvP","Normal","French")
a(106,"eu","temple-noir","Temple noir","PvP","Normal","French")
a(107,"eu","burning-legion","Burning Legion","PvP","Normal","English")
a(108,"eu","les-clairvoyants","Les Clairvoyants","PvE","RP","French")
a(109,"eu","tirion","Tirion","PvE","Normal","German")
a(110,"eu","rajaxx","Rajaxx","PvP","Normal","German")
a(111,"eu","blackhand","Blackhand","PvE","Normal","German")
a(112,"eu","dalaran","Dalaran","PvE","Normal","French")
a(113,"eu","destromath","Destromath","PvP","Normal","German")
a(114,"eu","pozzo-delleternita","Pozzo dell'Eternità","PvE","Normal")
a(115,"eu","mugthol","Mug'thol","PvP","Normal","German")
a(116,"eu","doomhammer","Doomhammer","PvE","Normal","English")
a(117,"eu","eonar","Eonar","PvE","Normal","English")
a(118,"eu","neptulon","Neptulon","PvP","Normal","English")
a(119,"eu","soulflayer","Soulflayer","PvP","Normal","Russian")
a(120,"eu","der-mithrilorden","Der Mithrilorden","PvE","RP","German")
a(121,"eu","howling-fjord","Howling Fjord","PvP","Normal","Russian")
a(122,"eu","nathrezim","Nathrezim","PvP","Normal","German")
a(123,"eu","ragnaros","Ragnaros","PvP","Normal","English")
a(124,"eu","borean-tundra","Borean Tundra","PvE","Normal","Russian")
a(125,"eu","darkspear","Darkspear","PvE","Normal","English")
a(126,"eu","azuremyst","Azuremyst","PvE","Normal","English")
a(127,"eu","varimathras","Varimathras","PvE","Normal","French")
a(128,"eu","bloodhoof","Bloodhoof","PvE","Normal","English")
a(129,"eu","das-syndikat","Das Syndikat","PvP","RP","German")
a(130,"eu","nozdormu","Nozdormu","PvE","Normal","German")
a(131,"eu","dragonmaw","Dragonmaw","PvP","Normal","English")
a(132,"eu","fordragon","Fordragon","PvE","Normal","Russian")
a(133,"eu","mazrigos","Mazrigos","PvE","Normal","English")
a(134,"eu","garrosh","Garrosh","PvE","Normal","German")
a(135,"eu","khadgar","Khadgar","PvE","Normal","English")
a(136,"eu","area-52","Area 52","PvE","Normal","German")
a(137,"eu","shattrath","Shattrath","PvE","Normal","German")
a(138,"eu","medivh","Medivh","PvE","Normal","French")
a(139,"eu","la-croisade-ecarlate","La Croisade écarlate","PvP","RP","French")
a(140,"eu","malfurion","Malfurion","PvE","Normal","German")
a(141,"eu","kargath","Kargath","PvE","Normal","German")
a(142,"eu","laughing-skull","Laughing Skull","PvP","Normal","English")
a(143,"eu","throkferoth","Throk'Feroth","PvP","Normal","French")
a(144,"eu","bloodfeather","Bloodfeather","PvP","Normal","English")
a(145,"eu","guldan","Gul'dan","PvP","Normal","German")
a(146,"eu","skullcrusher","Skullcrusher","PvP","Normal","English")
a(147,"eu","grim-batol","Grim Batol","PvP","Normal","English")
a(148,"eu","deepholm","Deepholm","PvP","Normal","Russian")
a(149,"eu","marecage-de-zangar","Marécage de Zangar","PvE","Normal","French")
a(150,"eu","ghostlands","Ghostlands","PvE","Normal","English")
a(151,"eu","vashj","Vashj","PvP","Normal","English")
a(152,"eu","malganis","Mal'Ganis","PvP","Normal","German")
a(153,"eu","nemesis","Nemesis","PvP","Normal")
a(154,"eu","zuljin","Zul'jin","PvP","Normal","Spanish")
a(155,"eu","zirkel-des-cenarius","Zirkel des Cenarius","PvE","RP","German")
a(156,"eu","ysera","Ysera","PvE","Normal","German")
a(157,"eu","wrathbringer","Wrathbringer","PvP","Normal","German")
a(158,"eu","khazgoroth","Khaz'goroth","PvE","Normal","German")
a(159,"eu","deathwing","Deathwing","PvP","Normal","English")
a(160,"eu","arygos","Arygos","PvE","Normal","German")
a(161,"eu","runetotem","Runetotem","PvE","Normal","English")
a(162,"eu","sunstrider","Sunstrider","PvP","Normal","English")
a(163,"eu","bronzebeard","Bronzebeard","PvE","Normal","English")
a(164,"eu","veknilash","Vek'nilash","PvE","Normal","English")
a(165,"eu","suramar","Suramar","PvE","Normal","French")
a(166,"eu","illidan","Illidan","PvP","Normal","French")
a(167,"eu","veklor","Vek'lor","PvP","Normal","German")
a(168,"eu","blackscar","Blackscar","PvP","Normal","Russian")
a(169,"eu","greymane","Greymane","PvP","Normal","Russian")
a(170,"eu","khaz-modan","Khaz Modan","PvE","Normal","French")
a(171,"eu","todeswache","Todeswache","PvE","RP","German")
a(172,"eu","the-maelstrom","The Maelstrom","PvP","Normal","English")
a(173,"eu","hellscream","Hellscream","PvE","Normal","English")
a(174,"eu","burning-blade","Burning Blade","PvP","Normal","English")
a(175,"eu","die-silberne-hand","Die Silberne Hand","PvE","RP","German")
a(176,"eu","nazjatar","Nazjatar","PvP","Normal","German")
a(177,"eu","eversong","Eversong","PvE","Normal","Russian")
a(178,"eu","aggramar","Aggramar","PvE","Normal","English")
a(179,"eu","shadowsong","Shadowsong","PvE","Normal","English")
a(180,"eu","drekthar","Drek'Thar","PvE","Normal","French")
a(181,"eu","goldrinn","Goldrinn","PvE","Normal","Russian")
a(182,"eu","kilrogg","Kilrogg","PvE","Normal","English")
a(183,"eu","dentarg","Dentarg","PvP","Normal","English")
a(184,"eu","ungoro","Un'Goro","PvE","Normal","German")
a(185,"eu","anachronos","Anachronos","PvE","Normal","English")
a(186,"eu","uldum","Uldum","PvP","Normal","Spanish")
a(187,"eu","dethecus","Dethecus","PvP","Normal","German")
a(188,"eu","ulduar","Ulduar","PvE","Normal","German")
a(189,"eu","proudmoore","Proudmoore","PvE","Normal","German")
a(190,"eu","amanthul","Aman'Thul","PvE","Normal","German")
a(191,"eu","tyrande","Tyrande","PvE","Normal","Spanish")
a(192,"eu","razuvious","Razuvious","PvP","Normal","Russian")
a(193,"eu","turalyon","Turalyon","PvE","Normal","English")
a(194,"eu","der-rat-von-dalaran","Der Rat von Dalaran","PvE","RP","German")
a(195,"eu","arathor","Arathor","PvE","Normal","English")
a(196,"eu","bladefist","Bladefist","PvP","Normal","English")
a(197,"eu","eitrigg","Eitrigg","PvE","Normal","French")
a(198,"eu","thunderhorn","Thunderhorn","PvE","Normal","English")
a(199,"eu","chamber-of-aspects","Chamber of Aspects","PvE","Normal","English")
a(200,"eu","azjolnerub","Azjol-Nerub","PvE","Normal","English")
a(201,"eu","draenor","Draenor","PvE","Normal","English")
a(202,"eu","festung-der-sturme","Festung der Stürme","PvP","Normal","German")
a(203,"eu","arthas","Arthas","PvP","Normal","German")
a(204,"eu","terenas","Terenas","PvE","Normal","English")
a(205,"eu","norgannon","Norgannon","PvE","Normal","German")
a(206,"eu","the-shatar","The Sha'tar","PvE","RP","English")
a(207,"eu","burning-steppes","Burning Steppes","PvP","Normal","English")
a(208,"eu","kul-tiras","Kul Tiras","PvE","Normal","English")
a(209,"eu","kragjin","Krag'jin","PvP","Normal","German")
a(210,"eu","elune","Elune","PvE","Normal","French")
a(211,"eu","aegwynn","Aegwynn","PvP","Normal","German")
a(212,"eu","teldrassil","Teldrassil","PvE","Normal","German")
a(213,"eu","tarren-mill","Tarren Mill","PvP","Normal","English")
a(214,"eu","nefarian","Nefarian","PvP","Normal","German")
a(215,"eu","sylvanas","Sylvanas","PvP","Normal","English")
a(216,"eu","stormreaver","Stormreaver","PvP","Normal","English")
a(217,"eu","hellfire","Hellfire","PvE","Normal","English")
a(218,"eu","darkmoon-faire","Darkmoon Faire","PvE","RP","English")
a(219,"eu","die-ewige-wacht","Die ewige Wacht","PvE","RP","German")
a(220,"eu","sporeggar","Sporeggar","PvP","RP","English")
a(221,"eu","korgall","Kor'gall","PvP","Normal","English")
a(222,"eu","exodar","Exodar","PvE","Normal","Spanish")
a(223,"eu","spinebreaker","Spinebreaker","PvP","Normal","English")
a(224,"eu","bronze-dragonflight","Bronze Dragonflight","PvE","Normal","English")
a(225,"eu","magtheridon","Magtheridon","PvE","Normal","English")
a(226,"eu","dragonblight","Dragonblight","PvE","Normal","English")
a(227,"eu","sanguino","Sanguino","PvP","Normal","Spanish")
a(228,"eu","colinas-pardas","Colinas Pardas","PvE","Normal","Spanish")
a(229,"eu","shattered-hand","Shattered Hand","PvP","Normal","English")
a(230,"eu","blackrock","Blackrock","PvP","Normal","German")
a(231,"eu","deathweaver","Deathweaver","PvP","Normal","Russian")
a(232,"eu","los-errantes","Los Errantes","PvE","RP","Spanish")
a(233,"eu","senjin","Sen'jin","PvE","Normal","German")
a(234,"eu","blades-edge","Blade's Edge","PvE","Normal","English")
a(235,"eu","eredar","Eredar","PvP","Normal","German")
a(236,"eu","dun-modr","Dun Modr","PvP","Normal","Spanish")
a(237,"eu","minahonda","Minahonda","PvE","Normal","Spanish")
a(238,"eu","frostwolf","Frostwolf","PvP","Normal","German")
a(239,"eu","crushridge","Crushridge","PvP","Normal","English")
a(240,"eu","conseil-des-ombres","Conseil des Ombres","PvP","RP","French")
a(241,"eu","lothar","Lothar","PvE","Normal","German")
a(242,"eu","the-venture-co","The Venture Co","PvP","RP","English")
a(243,"eu","genjuros","Genjuros","PvP","Normal","English")
a(244,"eu","aerie-peak","Aerie Peak","PvE","Normal","English")
a(245,"eu","durotan","Durotan","PvE","Normal","German")
a(246,"eu","chogall","Cho'gall","PvP","Normal","French")
a(247,"eu","blutkessel","Blutkessel","PvP","Normal","German")
a(248,"eu","frostmourne","Frostmourne","PvP","Normal","German")
a(249,"eu","les-sentinelles","Les Sentinelles","PvE","RP","French")
a(250,"eu","alexstrasza","Alexstrasza","PvE","Normal","German")
a(251,"eu","kazzak","Kazzak","PvP","Normal","English")
a(252,"eu","die-aldor","Die Aldor","PvE","RP","German")
a(253,"eu","anubarak","Anub'arak","PvP","Normal","German")
a(254,"eu","lightbringer","Lightbringer","PvE","Normal","English")
a(255,"eu","lich-king","Lich King","PvP","Normal","Russian")
a(256,"eu","kult-der-verdammten","Kult der Verdammten","PvP","RP","German")
a(257,"eu","krasus","Krasus","PvE","Normal","French")
a(258,"eu","arathi","Arathi","PvP","Normal","French")
a(259,"eu","karazhan","Karazhan","PvP","Normal","English")
a(260,"eu","bloodscalp","Bloodscalp","PvP","Normal","English")
a(261,"eu","kirin-tor","Kirin Tor","PvE","RP","French")
a(262,"eu","aggra-portugues","Aggra (Português)","PvP","Normal","Portuguese")
a(263,"eu","echsenkessel","Echsenkessel","PvP","Normal","German")
a(264,"eu","gordunni","Gordunni","PvP","Normal","Russian")
a(265,"eu","shendralar","Shen'dralar","PvP","Normal","Spanish")
a(266,"eu","garona","Garona","PvP","Normal","French")
a(267,"eu","dalvengyr","Dalvengyr","PvP","Normal","German")
a(268,"eu","confrerie-du-thorium","Confrérie du Thorium","PvE","RP","French")
a(269,"us","cenarion-circle","Cenarion Circle","PvE","RP","United States")
a(270,"us","archimonde","Archimonde","PvP","Normal","United States")
a(271,"us","agamaggan","Agamaggan","PvP","Normal","United States")
a(272,"us","burning-legion","Burning Legion","PvP","Normal","United States")
a(273,"us","thrall","Thrall","PvE","Normal","United States")
a(274,"us","khaz-modan","Khaz Modan","PvE","Normal","United States")
a(275,"us","hellscream","Hellscream","PvE","Normal","United States")
a(276,"us","blackhand","Blackhand","PvE","Normal","United States")
a(277,"us","burning-blade","Burning Blade","PvP","Normal","United States")
a(278,"us","destromath","Destromath","PvP","Normal","United States")
a(279,"us","stormrage","Stormrage","PvE","Normal","United States")
a(280,"us","mugthol","Mug'thol","PvP","Normal","United States")
a(281,"us","doomhammer","Doomhammer","PvE","Normal","United States")
a(282,"us","eonar","Eonar","PvE","Normal","United States")
a(283,"us","moon-guard","Moon Guard","PvE","RP","United States")
a(284,"us","dethecus","Dethecus","PvP","Normal","United States")
a(285,"us","gallywix","Gallywix","PvE","Normal","Brazil")
a(286,"us","trollbane","Trollbane","PvE","Normal","United States")
a(287,"us","ravenholdt","Ravenholdt","PvP","RP","United States")
a(288,"us","proudmoore","Proudmoore","PvE","Normal","United States")
a(289,"us","zuluhed","Zuluhed","PvP","Normal","United States")
a(290,"us","stonemaul","Stonemaul","PvP","Normal","United States")
a(291,"us","zuljin","Zul'jin","PvE","Normal","United States")
a(292,"us","amanthul","Aman'thul","PvE","Normal","Oceanic")
a(293,"us","zangarmarsh","Zangarmarsh","PvE","Normal","United States")
a(294,"us","nathrezim","Nathrezim","PvP","Normal","United States")
a(295,"us","ragnaros","Ragnaros","PvP","Normal","Latin America")
a(296,"us","borean-tundra","Borean Tundra","PvE","Normal","United States")
a(297,"us","silvermoon","Silvermoon","PvE","Normal","United States")
a(298,"us","akama","Akama","PvP","Normal","United States")
a(299,"us","emerald-dream","Emerald Dream","PvP","RP","United States")
a(300,"us","draka","Draka","PvE","Normal","United States")
a(301,"us","sisters-of-elune","Sisters of Elune","PvE","RP","United States")
a(302,"us","warsong","Warsong","PvP","Normal","United States")
a(303,"us","ysera","Ysera","PvE","Normal","United States")
a(304,"us","darkspear","Darkspear","PvP","Normal","United States")
a(305,"us","arathor","Arathor","PvE","Normal","United States")
a(306,"us","bladefist","Bladefist","PvE","Normal","United States")
a(307,"us","demon-soul","Demon Soul","PvP","Normal","United States")
a(308,"us","onyxia","Onyxia","PvP","Normal","United States")
a(309,"us","bloodhoof","Bloodhoof","PvE","Normal","United States")
a(310,"us","veknilash","Vek'nilash","PvE","Normal","United States")
a(311,"us","steamwheedle-cartel","Steamwheedle Cartel","PvE","RP","United States")
a(312,"us","azjolnerub","Azjol-Nerub","PvE","Normal","United States")
a(313,"us","dragonmaw","Dragonmaw","PvP","Normal","United States")
a(314,"us","dreadmaul","Dreadmaul","PvP","Normal","Oceanic")
a(315,"us","drakkari","Drakkari","PvP","Normal","Latin America")
a(316,"us","nazgrel","Nazgrel","PvE","Normal","United States")
a(317,"us","skullcrusher","Skullcrusher","PvP","Normal","United States")
a(318,"us","wildhammer","Wildhammer","PvP","Normal","United States")
a(319,"us","frostmane","Frostmane","PvP","Normal","United States")
a(320,"us","deathwing","Deathwing","PvP","Normal","United States")
a(321,"us","queldorei","Quel'dorei","PvE","Normal","United States")
a(322,"us","ysondre","Ysondre","PvP","Normal","United States")
a(323,"us","the-scryers","The Scryers","PvE","RP","United States")
a(324,"us","velen","Velen","PvE","Normal","United States")
a(325,"us","elune","Elune","PvE","Normal","United States")
a(326,"us","garrosh","Garrosh","PvE","Normal","United States")
a(327,"us","wyrmrest-accord","Wyrmrest Accord","PvE","RP","United States")
a(328,"us","cenarius","Cenarius","PvE","Normal","United States")
a(329,"us","vashj","Vashj","PvP","Normal","United States")
a(330,"us","uther","Uther","PvE","Normal","United States")
a(331,"us","stormreaver","Stormreaver","PvP","Normal","United States")
a(332,"us","undermine","Undermine","PvE","Normal","United States")
a(333,"us","gnomeregan","Gnomeregan","PvE","Normal","United States")
a(334,"us","shattered-halls","Shattered Halls","PvP","Normal","United States")
a(335,"us","ursin","Ursin","PvP","Normal","United States")
a(336,"us","altar-of-storms","Altar of Storms","PvP","Normal","United States")
a(337,"us","sargeras","Sargeras","PvP","Normal","United States")
a(338,"us","drakthul","Drak'thul","PvE","Normal","United States")
a(339,"us","turalyon","Turalyon","PvE","Normal","United States")
a(340,"us","tortheldrin","Tortheldrin","PvP","Normal","United States")
a(341,"us","blackwater-raiders","Blackwater Raiders","PvE","RP","United States")
a(342,"us","korialstrasz","Korialstrasz","PvE","Normal","United States")
a(343,"us","tol-barad","Tol Barad","PvP","Normal","Brazil")
a(344,"us","medivh","Medivh","PvE","Normal","United States")
a(345,"us","tichondrius","Tichondrius","PvP","Normal","United States")
a(346,"us","bonechewer","Bonechewer","PvP","Normal","United States")
a(347,"us","nesingwary","Nesingwary","PvE","Normal","United States")
a(348,"us","thunderlord","Thunderlord","PvP","Normal","United States")
a(349,"us","thaurissan","Thaurissan","PvP","Normal","Oceanic")
a(350,"us","thunderhorn","Thunderhorn","PvE","Normal","United States")
a(351,"us","barthilas","Barthilas","PvP","Normal","Oceanic")
a(352,"us","scarlet-crusade","Scarlet Crusade","PvE","RP","United States")
a(353,"us","the-venture-co","The Venture Co","PvP","RP","United States")
a(354,"us","magtheridon","Magtheridon","PvP","Normal","United States")
a(355,"us","daggerspine","Daggerspine","PvP","Normal","United States")
a(356,"us","kargath","Kargath","PvE","Normal","United States")
a(357,"us","maelstrom","Maelstrom","PvP","RP","United States")
a(358,"us","laughing-skull","Laughing Skull","PvP","Normal","United States")
a(359,"us","dragonblight","Dragonblight","PvE","Normal","United States")
a(360,"us","garithos","Garithos","PvP","Normal","United States")
a(361,"us","caelestrasz","Caelestrasz","PvE","Normal","Oceanic")
a(362,"us","the-forgotten-coast","The Forgotten Coast","PvP","Normal","United States")
a(363,"us","spirestone","Spirestone","PvP","Normal","United States")
a(364,"us","blackrock","Blackrock","PvP","Normal","United States")
a(365,"us","shuhalo","Shu'halo","PvE","Normal","United States")
a(366,"us","farstriders","Farstriders","PvE","RP","United States")
a(367,"us","guldan","Gul'dan","PvP","Normal","United States")
a(368,"us","moknathal","Mok'Nathal","PvE","Normal","United States")
a(369,"us","kelthuzad","Kel'Thuzad","PvP","Normal","United States")
a(370,"us","terokkar","Terokkar","PvE","Normal","United States")
a(371,"us","terenas","Terenas","PvE","Normal","United States")
a(372,"us","lightninghoof","Lightninghoof","PvP","RP","United States")
a(373,"us","tanaris","Tanaris","PvE","Normal","United States")
a(374,"us","suramar","Suramar","PvE","Normal","United States")
a(375,"us","jubeithos","Jubei'Thos","PvP","Normal","Oceanic")
a(376,"us","jaedenar","Jaedenar","PvP","Normal","United States")
a(377,"us","stormscale","Stormscale","PvP","Normal","United States")
a(378,"us","dawnbringer","Dawnbringer","PvE","Normal","United States")
a(379,"us","twisting-nether","Twisting Nether","PvP","RP","United States")
a(380,"us","winterhoof","Winterhoof","PvE","Normal","United States")
a(381,"us","shadowmoon","Shadowmoon","PvP","Normal","United States")
a(382,"us","boulderfist","Boulderfist","PvP","Normal","United States")
a(383,"us","staghelm","Staghelm","PvE","Normal","United States")
a(384,"us","spinebreaker","Spinebreaker","PvP","Normal","United States")
a(385,"us","feathermoon","Feathermoon","PvE","RP","United States")
a(386,"us","ravencrest","Ravencrest","PvE","Normal","United States")
a(387,"us","blood-furnace","Blood Furnace","PvP","Normal","United States")
a(388,"us","windrunner","Windrunner","PvE","Normal","United States")
a(389,"us","silver-hand","Silver Hand","PvE","RP","United States")
a(390,"us","baelgun","Baelgun","PvE","Normal","United States")
a(391,"us","shattered-hand","Shattered Hand","PvP","Normal","United States")
a(392,"us","perenolde","Perenolde","PvE","Normal","United States")
a(393,"us","echo-isles","Echo Isles","PvE","Normal","United States")
a(394,"us","uldaman","Uldaman","PvE","Normal","United States")
a(395,"us","ghostlands","Ghostlands","PvE","Normal","United States")
a(396,"us","lethon","Lethon","PvP","Normal","United States")
a(397,"us","dark-iron","Dark Iron","PvP","Normal","United States")
a(398,"us","durotan","Durotan","PvE","Normal","United States")
a(399,"us","shandris","Shandris","PvE","Normal","United States")
a(400,"us","black-dragonflight","Black Dragonflight","PvP","Normal","United States")
a(401,"us","auchindoun","Auchindoun","PvP","Normal","United States")
a(402,"us","shadowsong","Shadowsong","PvE","Normal","United States")
a(403,"us","balnazzar","Balnazzar","PvP","Normal","United States")
a(404,"us","drenden","Drenden","PvE","Normal","United States")
a(405,"us","hakkar","Hakkar","PvP","Normal","United States")
a(406,"us","arygos","Arygos","PvE","Normal","United States")
a(407,"us","shadow-council","Shadow Council","PvE","RP","United States")
a(408,"us","lothar","Lothar","PvE","Normal","United States")
a(409,"us","anvilmar","Anvilmar","PvE","Normal","United States")
a(410,"us","senjin","Sen'jin","PvE","Normal","United States")
a(411,"us","kaelthas","Kael'Thas","PvE","Normal","United States")
a(412,"us","illidan","Illidan","PvP","Normal","United States")
a(413,"us","scilla","Scilla","PvP","Normal","United States")
a(414,"us","nemesis","Nemesis","PvP","Normal","Brazil")
a(415,"us","greymane","Greymane","PvE","Normal","United States")
a(416,"us","detheroc","Detheroc","PvP","Normal","United States")
a(417,"us","thorium-brotherhood","Thorium Brotherhood","PvE","RP","United States")
a(418,"us","saurfang","Saurfang","PvE","Normal","Oceanic")
a(419,"us","runetotem","Runetotem","PvE","Normal","United States")
a(420,"us","rivendare","Rivendare","PvP","Normal","United States")
a(421,"us","executus","Executus","PvP","Normal","United States")
a(422,"us","smolderthorn","Smolderthorn","PvP","Normal","United States")
a(423,"us","azuremyst","Azuremyst","PvE","Normal","United States")
a(424,"us","aggramar","Aggramar","PvE","Normal","United States")
a(425,"us","norgannon","Norgannon","PvE","Normal","United States")
a(426,"us","nazjatar","Nazjatar","PvP","Normal","United States")
a(427,"us","nordrassil","Nordrassil","PvE","Normal","United States")
a(428,"us","anubarak","Anub'arak","PvP","Normal","United States")
a(429,"us","dentarg","Dentarg","PvE","Normal","United States")
a(430,"us","gurubashi","Gurubashi","PvP","Normal","United States")
a(431,"us","nerzhul","Ner'zhul","PvP","Normal","United States")
a(432,"us","nagrand","Nagrand","PvE","Normal","Oceanic")
a(433,"us","muradin","Muradin","PvE","Normal","United States")
a(434,"us","korgath","Korgath","PvP","Normal","United States")
a(435,"us","malfurion","Malfurion","PvE","Normal","United States")
a(436,"us","gorefiend","Gorefiend","PvP","Normal","United States")
a(437,"us","mannoroth","Mannoroth","PvP","Normal","United States")
a(438,"us","malygos","Malygos","PvE","Normal","United States")
a(439,"us","darrowmere","Darrowmere","PvE","Normal","United States")
a(440,"us","lightbringer","Lightbringer","PvE","Normal","United States")
a(441,"us","anetheron","Anetheron","PvP","Normal","United States")
a(442,"us","blackwing-lair","Blackwing Lair","PvP","Normal","United States")
a(443,"us","eitrigg","Eitrigg","PvE","Normal","United States")
a(444,"us","misha","Misha","PvE","Normal","United States")
a(445,"us","malganis","Mal'Ganis","PvP","Normal","United States")
a(446,"us","gilneas","Gilneas","PvE","Normal","United States")
a(447,"us","draenor","Draenor","PvE","Normal","United States")
a(448,"us","alleria","Alleria","PvE","Normal","United States")
a(449,"us","the-underbog","The Underbog","PvP","Normal","United States")
a(450,"us","madoran","Madoran","PvE","Normal","United States")
a(451,"us","hydraxis","Hydraxis","PvE","Normal","United States")
a(452,"us","sentinels","Sentinels","PvE","RP","United States")
a(453,"us","kilrogg","Kilrogg","PvE","Normal","United States")
a(454,"us","kul-tiras","Kul Tiras","PvE","Normal","United States")
a(455,"us","duskwood","Duskwood","PvE","Normal","United States")
a(456,"us","lightnings-blade","Lightning's Blade","PvP","Normal","United States")
a(457,"us","aegwynn","Aegwynn","PvP","Normal","United States")
a(458,"us","gundrak","Gundrak","PvP","Normal","Oceanic")
a(459,"us","moonrunner","Moonrunner","PvE","Normal","United States")
a(460,"us","kirin-tor","Kirin Tor","PvE","RP","United States")
a(461,"us","llane","Llane","PvE","Normal","United States")
a(462,"us","kiljaeden","Kil'Jaeden","PvP","Normal","United States")
a(463,"us","azralon","Azralon","PvP","Normal","Brazil")
a(464,"us","khazgoroth","Khaz'goroth","PvE","Normal","Oceanic")
a(465,"us","khadgar","Khadgar","PvE","Normal","United States")
a(466,"us","whisperwind","Whisperwind","PvE","Normal","United States")
a(467,"us","aerie-peak","Aerie Peak","PvE","Normal","United States")
a(468,"us","exodar","Exodar","PvE","Normal","United States")
a(469,"us","firetree","Firetree","PvP","Normal","United States")
a(470,"us","dalaran","Dalaran","PvE","Normal","United States")
a(471,"us","azgalor","Azgalor","PvP","Normal","United States")
a(472,"us","argent-dawn","Argent Dawn","PvE","RP","United States")
a(473,"us","uldum","Uldum","PvE","Normal","United States")
a(474,"us","skywall","Skywall","PvE","Normal","United States")
a(475,"us","dathremar","Dath'Remar","PvE","Normal","Oceanic")
a(476,"us","malorne","Malorne","PvP","Normal","United States")
a(477,"us","bronzebeard","Bronzebeard","PvE","Normal","United States")
a(478,"us","icecrown","Icecrown","PvE","Normal","United States")
a(479,"us","maiev","Maiev","PvP","Normal","United States")
a(480,"us","blades-edge","Blade's Edge","PvE","Normal","United States")
a(481,"us","chromaggus","Chromaggus","PvP","Normal","United States")
a(482,"us","frostwolf","Frostwolf","PvP","Normal","United States")
a(483,"us","haomarush","Haomarush","PvP","Normal","United States")
a(484,"us","grizzly-hills","Grizzly Hills","PvE","Normal","United States")
a(485,"us","crushridge","Crushridge","PvP","Normal","United States")
a(486,"us","draktharon","Drak'Tharon","PvP","Normal","United States")
a(487,"us","fizzcrank","Fizzcrank","PvE","Normal","United States")
a(488,"us","coilfang","Coilfang","PvP","Normal","United States")
a(489,"us","gorgonnash","Gorgonnash","PvP","Normal","United States")
a(490,"us","quelthalas","Quel'Thalas","PvE","Normal","Latin America")
a(491,"us","goldrinn","Goldrinn","PvE","Normal","Brazil")
a(492,"us","chogall","Cho'gall","PvP","Normal","United States")
a(493,"us","arthas","Arthas","PvP","Normal","United States")
a(494,"us","andorhal","Andorhal","PvP","Normal","United States")
a(495,"us","hyjal","Hyjal","PvE","Normal","United States")
a(496,"us","alexstrasza","Alexstrasza","PvE","Normal","United States")
a(497,"us","garona","Garona","PvE","Normal","United States")
a(498,"us","alterac-mountains","Alterac Mountains","PvP","Normal","United States")
a(499,"us","galakrond","Galakrond","PvE","Normal","United States")
a(500,"us","fenris","Fenris","PvE","Normal","United States")
a(501,"us","cairne","Cairne","PvE","Normal","United States")
a(502,"us","dunemaul","Dunemaul","PvP","Normal","United States")
a(503,"us","frostmourne","Frostmourne","PvP","Normal","Oceanic")
a(504,"us","eredar","Eredar","PvP","Normal","United States")
a(505,"us","area-52","Area 52","PvE","Normal","United States")
a(506,"us","bloodscalp","Bloodscalp","PvP","Normal","United States")
a(507,"us","azshara","Azshara","PvP","Normal","United States")
a(508,"us","rexxar","Rexxar","PvE","Normal","United States")
a(509,"us","antonidas","Antonidas","PvE","Normal","United States")
a(510,"us","bleeding-hollow","Bleeding Hollow","PvP","Normal","United States")
a(511,"us","eldrethalas","Eldre'Thalas","PvE","Normal","United States")
a(512,"us","earthen-ring","Earthen Ring","PvE","RP","United States")
a(513,"us","kalecgos","Kalecgos","PvP","Normal","United States")
a(514,"us","dalvengyr","Dalvengyr","PvP","Normal","United States")